#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIRECTORY="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPOSITORY_ROOT="$(cd -- "${SCRIPT_DIRECTORY}/.." && pwd)"
cd "${REPOSITORY_ROOT}"

docker compose --env-file .env.example -f deploy/local/compose.yaml config --quiet
git diff --check

if [[ -n "$(git ls-files docs .agents)" ]]; then
  echo "Ignored docs/ or .agents/ content is present in the Git index." >&2
  exit 1
fi

# Authorship and tooling provenance. See CONTRIBUTING.md.
# Functional provider IDs and API URIs are permitted; vendor names remain forbidden in contributor
# metadata and tooling attribution. Trailer/footer and prose attribution are checked in tracked files.
PROVENANCE_TRAILER='^[^[:alnum:]]*(co-authored-by|generated by|generated with|assisted by|assisted-by)'
PROVENANCE_ATTRIBUTION='(generated|assisted|co-authored|written|created|authored)[[:space:]-]*(by|with|using)[[:space:]]*(claude|anthropic|copilot|chatgpt|openai|gemini)'
PROVENANCE_EXCLUDED='CONTRIBUTING.md .github/pull_request_template.md scripts/check-quality-gates.sh'

PROVENANCE_SCANNED="$(git ls-files | grep -vxF -f <(printf '%s\n' ${PROVENANCE_EXCLUDED}))"
PROVENANCE_FILE_HITS="$(
  git grep -InE -i "${PROVENANCE_TRAILER}" -- ${PROVENANCE_SCANNED} || true
  git grep -InE -i "${PROVENANCE_ATTRIBUTION}" -- ${PROVENANCE_SCANNED} || true
)"
if [[ -n "${PROVENANCE_FILE_HITS}" ]]; then
  echo "Tracked files attribute authorship to a tool:" >&2
  echo "${PROVENANCE_FILE_HITS}" >&2
  exit 1
fi

PROVENANCE_HISTORY="$(git log --format='%H%n%an <%ae>%n%cn <%ce>%n%B')"
PROVENANCE_COMMIT_HITS="$(
  grep -inE "${PROVENANCE_TRAILER}" <<<"${PROVENANCE_HISTORY}" || true
  grep -inE "${PROVENANCE_ATTRIBUTION}" <<<"${PROVENANCE_HISTORY}" || true
)"
if [[ -n "${PROVENANCE_COMMIT_HITS}" ]]; then
  echo "Commit metadata or messages attribute authorship to a tool:" >&2
  echo "${PROVENANCE_COMMIT_HITS}" >&2
  exit 1
fi

# One acceptance proof per delivered stage, plus the concurrency smoke. A proof that stops running
# must fail the gate rather than pass quietly.
FAILSAFE_REPORTS="master-data-service/bootstrap-master-service/target/failsafe-reports"
for report in \
  "${FAILSAFE_REPORTS}/TEST-io.stewardmesh.masterdata.bootstrap.SupplierIntakeEndToEndIT.xml" \
  "${FAILSAFE_REPORTS}/TEST-io.stewardmesh.masterdata.bootstrap.IdentityResolutionEndToEndIT.xml" \
  "${FAILSAFE_REPORTS}/TEST-io.stewardmesh.masterdata.bootstrap.Phase3GovernedExecutionEndToEndIT.xml" \
  "${FAILSAFE_REPORTS}/TEST-io.stewardmesh.masterdata.bootstrap.SupplierIntakeLoadSmokeIT.xml"; do
  [[ -f "${report}" ]] || {
    echo "Required E2E report was not generated: ${report}" >&2
    exit 1
  }
  grep -q 'failures="0"' "${report}" && grep -q 'errors="0"' "${report}" || {
    echo "Required E2E proof did not pass: ${report}" >&2
    exit 1
  }
done

# Every scope the published MCP contract requires must be obtainable from the local realm, or the
# documented local stack cannot exercise the governed tools it ships.
MISSING_SCOPES="$(python3 - <<'PYTHON'
import json
import sys

contract = json.load(open("contracts/mcp/governed-action-plan-tools-v1.json"))
realm = json.load(open("deploy/local/keycloak/stewardmesh-realm.json"))

required = {tool["requiredScope"] for tool in contract["tools"]}
declared = {scope["name"] for scope in realm["clientScopes"]}
grantable = {scope for client in realm["clients"] for scope in client["defaultClientScopes"]}

missing = sorted((required - declared) | (required - grantable))
sys.stdout.write("\n".join(missing))
PYTHON
)"
if [[ -n "${MISSING_SCOPES}" ]]; then
  echo "The local Keycloak realm cannot grant MCP scopes required by the contract:" >&2
  echo "${MISSING_SCOPES}" >&2
  exit 1
fi

COVERAGE_CSV="master-data-service/bootstrap-master-service/target/site/jacoco-aggregate/jacoco.csv"
[[ -f "${COVERAGE_CSV}" ]] || {
  echo "Aggregate JaCoCo report was not generated." >&2
  exit 1
}

COVERAGE_SUMMARY="$(awk -F, '
    NR > 1 {
        instruction_missed += $4; instruction_covered += $5
        branch_missed += $6; branch_covered += $7
        line_missed += $8; line_covered += $9
    }
    END {
        instruction_total = instruction_missed + instruction_covered
        branch_total = branch_missed + branch_covered
        line_total = line_missed + line_covered
        instruction_percent = instruction_total ? 100 * instruction_covered / instruction_total : 0
        branch_percent = branch_total ? 100 * branch_covered / branch_total : 0
        line_percent = line_total ? 100 * line_covered / line_total : 0
        printf "instructions=%.1f%% branches=%.1f%% lines=%.1f%%", \
            instruction_percent, branch_percent, line_percent
        if (line_percent < 80) exit 2
    }
' "${COVERAGE_CSV}")" || {
  echo "Aggregate line coverage is below the 80% Phase 2 review floor." >&2
  exit 1
}

echo "Repository quality gates passed (${COVERAGE_SUMMARY})."
